databases:
  - name: Food
    databaseName: food_qcsg
    user: food_qcsg_user

services:
  - type: web
    name: feeds
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: food_qcsg
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false